#!/usr/bin/env node

/**
 * Postbuild step for `expo export --platform web` (AD-4, AD-5).
 *
 * 1. Copies dist/index.html -> dist/404.html (GitHub Pages SPA-routing
 *    fallback; byte-identical copy is the standard GH Pages pattern).
 * 2. Runs workbox-build's generateSW against the real dist/ output so the
 *    precache manifest is never hand-maintained -- and asserts the
 *    precached entry count equals dist/'s real file count (minus
 *    service-worker.js itself), failing loud on mismatch so a
 *    silently-excluded asset can't ship undetected.
 */

const fs = require("fs");
const path = require("path");
const { generateSW } = require("workbox-build");

const root = process.cwd();
const distDir = path.join(root, "dist");
const indexHtmlPath = path.join(distDir, "index.html");
const notFoundHtmlPath = path.join(distDir, "404.html");
const swDest = path.join(distDir, "service-worker.js");

// Workbox's own generated infrastructure -- not app assets, so they are
// never precached (a service worker doesn't need to cache itself) and must
// be excluded from the real-file-count baseline too, or the count-vs-count
// assertion below would always fail against workbox-build's own output.
const WORKBOX_RUNTIME_PATTERN = /^workbox-.*\.js(\.map)?$/;

// _expo/.routes.json is real `expo export` output, but workbox-build's
// underlying glob matching (the `glob` package, no exposed `dot` option in
// generateSW's config) never matches dotfiles, so it can never be precached
// regardless of globPatterns/globIgnores. Confirmed not runtime-fetched by
// the app shell (dev/build-tooling metadata only, `{"redirects":[]}`) --
// explicit, named exclusion per AD-5, not a silent one.
const KNOWN_UNPRECACHEABLE_RELATIVE_PATHS = new Set(["_expo/.routes.json"]);

function countFiles(dir, relativeTo) {
  let count = 0;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    const relativePath = path
      .relative(relativeTo, fullPath)
      .split(path.sep)
      .join("/");
    if (entry.isSymbolicLink()) {
      // entry.isDirectory() is false for a symlink itself -- stat the
      // target so a symlinked directory's contents aren't silently
      // dropped from the real-file-count baseline.
      count += fs.statSync(fullPath).isDirectory()
        ? countFiles(fullPath, relativeTo)
        : 1;
    } else if (entry.isDirectory()) {
      count += countFiles(fullPath, relativeTo);
    } else if (
      entry.name === "service-worker.js" ||
      entry.name === "service-worker.js.map" ||
      WORKBOX_RUNTIME_PATTERN.test(entry.name) ||
      KNOWN_UNPRECACHEABLE_RELATIVE_PATHS.has(relativePath)
    ) {
      // excluded, named above
    } else {
      count += 1;
    }
  }
  return count;
}

async function main() {
  if (!fs.existsSync(indexHtmlPath)) {
    console.error(
      `❌ dist/index.html not found -- run "expo export --platform web" first.`
    );
    process.exit(1);
  }

  // AD-4: 404.html is a byte-identical copy of the built index.html, so
  // GitHub Pages' static 404 fallback serves the real app shell.
  fs.copyFileSync(indexHtmlPath, notFoundHtmlPath);
  console.log("📄 dist/404.html generated (copy of dist/index.html).");

  // AD-5: precache manifest generated by Workbox, never hand-maintained.
  const { count, warnings } = await generateSW({
    globDirectory: distDir,
    globPatterns: ["**/*"],
    globIgnores: ["service-worker.js"],
    swDest,
    // Workbox's 2 MiB default would drop the main JS bundle (~2.0 MiB and
    // growing) from the precache, breaking AD-5's 100%-precached invariant.
    // Set explicitly rather than left implicit so bundle growth doesn't
    // silently cross an unowned default.
    maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
    // AD-4: the service worker intercepts navigations before GitHub Pages'
    // static 404.html fallback can, so without this an offline deep link to
    // a non-root route matches no precache entry and fails. Dynamic routes
    // export as literal [id].html files, so index.html is the only shell
    // that can client-render an arbitrary route.
    navigateFallback: "index.html",
    navigateFallbackDenylist: [/_expo\//],
  });

  if (warnings && warnings.length > 0) {
    for (const warning of warnings) {
      console.error(`⚠️  workbox-build warning: ${warning}`);
    }
    process.exit(1);
  }

  const realFileCount = countFiles(distDir, distDir);

  if (count !== realFileCount) {
    console.error(
      `❌ Precache count mismatch: workbox-build precached ${count} file(s), ` +
        `but dist/ contains ${realFileCount} file(s) (excluding service-worker.js, ` +
        `its sourcemap, the workbox-*.js runtime chunk, and _expo/.routes.json -- ` +
        `see postbuild-web.js's named exclusion list). ` +
        `A build asset may be silently excluded from the offline cache.`
    );
    process.exit(1);
  }

  console.log(
    `✅ dist/service-worker.js generated -- ${count} file(s) precached, matches dist/'s real file count.`
  );
}

main().catch((error) => {
  console.error(`❌ Error in postbuild-web: ${error?.message ?? String(error)}`);
  process.exit(1);
});
